[workspace]
channels = ["conda-forge"]
name = "pytest-ci"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
pytest = ">=9.0.3,<10"
cmake = ">=3.22"

[tasks]
test = { cmd = "cmake -B build"}
